[project]
name = sarboledaq-courses
authors = [{name: "Santiago Arboleda", email: "sarboledaq@unal.edu.co}]
dynamic = ["version", "description"]

[project.optional-dependencies]
doc = ["sphinx~=4.5.0"]